#!/usr/bin/env python3
"""Generate assets/live.svg from the public GitHub API.

Designed for the annel0/annel0 profile repository. It uses only the Python
standard library and the workflow-provided GITHUB_TOKEN.
"""

from __future__ import annotations

import html
import json
import os
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

USER = "annel0"
OUT = Path(__file__).resolve().parents[1] / "assets" / "live.svg"
TOKEN = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")


def api(path: str):
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": f"{USER}-profile-readme",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    req = urllib.request.Request(f"https://api.github.com{path}", headers=headers)
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def all_repos():
    repos = []
    page = 1
    while True:
        chunk = api(f"/users/{USER}/repos?per_page=100&page={page}&sort=pushed&type=owner")
        repos.extend(chunk)
        if len(chunk) < 100:
            break
        page += 1
    return repos


def fmt_date(value: str | None) -> str:
    if not value:
        return "n/a"
    dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
    return dt.strftime("%Y-%m-%d")


def esc(value) -> str:
    return html.escape(str(value), quote=True)


def main() -> None:
    user = api(f"/users/{USER}")
    repos = all_repos()
    source_repos = [r for r in repos if not r.get("fork")]
    total_stars = sum(int(r.get("stargazers_count", 0)) for r in repos)
    total_forks = sum(int(r.get("forks_count", 0)) for r in repos)
    pushed = [r for r in repos if r.get("pushed_at")]
    latest = max(pushed, key=lambda r: r["pushed_at"]) if pushed else None
    latest_name = latest["name"] if latest else "n/a"
    latest_date = fmt_date(latest["pushed_at"] if latest else None)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    metrics = [
        ("PUBLIC REPOS", user.get("public_repos", len(repos))),
        ("SOURCE REPOS", len(source_repos)),
        ("STARS ON REPOS", total_stars),
        ("FORKS OF REPOS", total_forks),
    ]

    cells = []
    x_positions = [48, 326, 604, 882]
    for x, (label, value) in zip(x_positions, metrics):
        cells.append(
            f'<text x="{x}" y="91" class="value metric" font-size="30">{esc(value)}</text>'
            f'<text x="{x}" y="119" class="label" font-size="13">{esc(label)}</text>'
        )

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="205" viewBox="0 0 1200 205" role="img" aria-labelledby="title desc">
  <title id="title">annel0 profile telemetry</title>
  <desc id="desc">Public GitHub repository metrics generated automatically.</desc>
  <style>
    .bg {{ fill: #f6f8fa; stroke: #d0d7de; }}
    .divider {{ stroke: #d8dee4; }}
    .label {{ fill: #57606a; font-family: ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; letter-spacing: .7px; }}
    .value {{ fill: #1f2328; font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif; font-weight: 650; }}
    .muted {{ fill: #6e7781; font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif; }}
    .accent {{ fill: #0969da; font-family: ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-weight: 700; }}
    @media (prefers-color-scheme: dark) {{
      .bg {{ fill: #0d1117; stroke: #30363d; }}
      .divider {{ stroke: #21262d; }}
      .label {{ fill: #8b949e; }}
      .value {{ fill: #f0f6fc; }}
      .muted {{ fill: #8b949e; }}
      .accent {{ fill: #58a6ff; }}
    }}
  </style>
  <rect class="bg" x="1" y="1" width="1198" height="203" rx="20"/>
  <text x="48" y="43" class="accent" font-size="17">PROFILE TELEMETRY</text>
  <line class="divider" x1="48" y1="57" x2="1152" y2="57"/>
  {''.join(cells)}
  <line class="divider" x1="48" y1="139" x2="1152" y2="139"/>
  <text x="48" y="171" class="muted" font-size="15">latest push: <tspan class="value">{esc(latest_name)}</tspan> · {esc(latest_date)}</text>
  <text x="1152" y="171" text-anchor="end" class="label" font-size="12">updated {esc(generated)}</text>
  <text x="48" y="192" class="label" font-size="11">generated by GitHub Actions · GitHub API · no third-party stats service</text>
</svg>'''

    OUT.write_text(svg, encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
